# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d75dbd8ee4cf4808a135575b6a97bb3803fe707a0346201981f7eadb964611f9a29180f3c0e0b792aa96b15321f1e26fa9531f7df7aa159298bb5bdd8d24eea

test:
  secret_key_base: 79817a70b3dae51c0c5a807df6a0a91cfdc5e302e7a13eaec7479a3ba4436799d3e90070e2e8c49a3773e0857bc48d45abf0b5fd8e5da9ca5ffcec9841333a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
